project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "CMMR Developer News"
  site-url: "https://cmmr.github.io"

  # Navigation Bar
  navbar:
    right:
      - icon: github
        href: https://github.com/cmmr
      - icon: rss
        href: index.xml

  # Organization Sidebar
  sidebar:
    style: "docked"
    contents:

      - section: "Research Tools"
        contents:
          - text: "**EsViritu**<small>Viral Discovery</small>"
            href: https://github.com/cmmr/EsViritu
          - text: "**virmap**<small>Taxonomic Mapping</small>"
            href: https://github.com/cmmr/virmap
          - text: "**Marker-MAGu**<small>Metagenomic Profiling</small>"
            href: https://github.com/cmmr/Marker-MAGu
          - text: "**rbiom**<small>Microbiome Analysis</small>"
            href: https://cmmr.github.io/rbiom
          - text: "**ecodive**<small>Ecological Diversity</small>"
            href: https://cmmr.github.io/ecodive
          - text: "**h5lite**<small>HDF5 Interface</small>"
            href: https://cmmr.github.io/h5lite
          - text: "**fillpattern**<small>ggplot2 Pattern Fills</small>"
            href: https://github.com/cmmr/fillpattern
      
      - "---"

      - section: "Syndication"
        contents:
          - text: "**R-bloggers**"
            href: https://www.r-bloggers.com/
          - text: "**R Weekly**"
            href: https://rweekly.org/
      
      - "---"
  

  # Footer with Official Info
  page-footer:
    background: light
    left: "© 2026 CMMR / Baylor College of Medicine"
    right:
      - text: "Alkek Center for Metagenomics & Microbiome Research"
        href: https://www.bcm.edu/research/research-centers/alkek-center-for-metagenomics-and-microbiome-research

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-after-body: analytics.html
